name: Build and Package Docker image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main' # Adjust the default branch if needed

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: cd
        run: cd ./backend/

      - name: Build Go package
        run: go build -o server . -t server

      - name: Package into tar file
        run: tar -czf server.tar.gz server
        # Adjust "yourapp" to the name of your Go executable

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tar docker image
          path: server.tar.gz

