name: Build and Package Docker image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'master'

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: cd ./backend/ && docker build -t server .

      - name: Package into tar file
        run:  docker save --output="server.tar" server

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tar docker image
          path: server.tar

